### ISSUE TITLE
field name mismatch in Memorandum PDF

### ISSUE THREAD

**Issue by mscarey** [Juris-M/indigobook#2]
Thanks for adding this documentation. 

In the example feedback popup on page 2 of ib-edit.pdf, the data in the last 4 fields doesn't match the field names.

**Comment by fbennett** [comment]
Thanks for spotting that! I've replaced the graphic with a screenshot. The original was a (sloppy) wireframe, doodled up in Gimp before I revisited the work and realized I already had a sample page up.
